# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.grpc.v1 import account_setup_pb2 as altastata_dot_grpc_dot_v1_dot_account__setup__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/grpc/v1/account_setup_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountSetupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupportedAccountTypes = channel.unary_unary(
                '/altastata.v1.AccountSetupService/GetSupportedAccountTypes',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesResponse.FromString,
                _registered_method=True)
        self.GenerateKeys = channel.unary_unary(
                '/altastata.v1.AccountSetupService/GenerateKeys',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/altastata.v1.AccountSetupService/ChangePassword',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordResponse.FromString,
                _registered_method=True)
        self.UpdateUserProperties = channel.unary_unary(
                '/altastata.v1.AccountSetupService/UpdateUserProperties',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesResponse.FromString,
                _registered_method=True)
        self.ExportAccount = channel.unary_unary(
                '/altastata.v1.AccountSetupService/ExportAccount',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountResponse.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/altastata.v1.AccountSetupService/DeleteAccount',
                request_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountResponse.FromString,
                _registered_method=True)


class AccountSetupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSupportedAccountTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountSetupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupportedAccountTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedAccountTypes,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesResponse.SerializeToString,
            ),
            'GenerateKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKeys,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordResponse.SerializeToString,
            ),
            'UpdateUserProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProperties,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesResponse.SerializeToString,
            ),
            'ExportAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAccount,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.AccountSetupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.AccountSetupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountSetupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSupportedAccountTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/GetSupportedAccountTypes',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GetSupportedAccountTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/GenerateKeys',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.GenerateKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/ChangePassword',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ChangePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/UpdateUserProperties',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.UpdateUserPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/ExportAccount',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.ExportAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.AccountSetupService/DeleteAccount',
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_account__setup__pb2.DeleteAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
