# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altastata/grpc/v1/s3_credentials.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'altastata/grpc/v1/s3_credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&altastata/grpc/v1/s3_credentials.proto\x12\x0c\x61ltastata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n\x17IssueCredentialsRequest\x12\r\n\x05label\x18\x01 \x01(\t\"L\n\x18IssueCredentialsResponse\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\x12\x19\n\x11secret_access_key\x18\x02 \x01(\t\"i\n\x11\x43redentialSummary\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1a\n\x18ListMyCredentialsRequest\"Q\n\x19ListMyCredentialsResponse\x12\x34\n\x0b\x63redentials\x18\x01 \x03(\x0b\x32\x1f.altastata.v1.CredentialSummary\"1\n\x18RevokeCredentialsRequest\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\"\x1b\n\x19RevokeCredentialsResponse2\xc5\x02\n\x14S3CredentialsService\x12\x61\n\x10IssueCredentials\x12%.altastata.v1.IssueCredentialsRequest\x1a&.altastata.v1.IssueCredentialsResponse\x12\x64\n\x11ListMyCredentials\x12&.altastata.v1.ListMyCredentialsRequest\x1a\'.altastata.v1.ListMyCredentialsResponse\x12\x64\n\x11RevokeCredentials\x12&.altastata.v1.RevokeCredentialsRequest\x1a\'.altastata.v1.RevokeCredentialsResponseB0\n\x18\x63om.altastata.grpc.protoB\x12S3CredentialsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altastata.grpc.v1.s3_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.altastata.grpc.protoB\022S3CredentialsProtoP\001'
  _globals['_ISSUECREDENTIALSREQUEST']._serialized_start=89
  _globals['_ISSUECREDENTIALSREQUEST']._serialized_end=129
  _globals['_ISSUECREDENTIALSRESPONSE']._serialized_start=131
  _globals['_ISSUECREDENTIALSRESPONSE']._serialized_end=207
  _globals['_CREDENTIALSUMMARY']._serialized_start=209
  _globals['_CREDENTIALSUMMARY']._serialized_end=314
  _globals['_LISTMYCREDENTIALSREQUEST']._serialized_start=316
  _globals['_LISTMYCREDENTIALSREQUEST']._serialized_end=342
  _globals['_LISTMYCREDENTIALSRESPONSE']._serialized_start=344
  _globals['_LISTMYCREDENTIALSRESPONSE']._serialized_end=425
  _globals['_REVOKECREDENTIALSREQUEST']._serialized_start=427
  _globals['_REVOKECREDENTIALSREQUEST']._serialized_end=476
  _globals['_REVOKECREDENTIALSRESPONSE']._serialized_start=478
  _globals['_REVOKECREDENTIALSRESPONSE']._serialized_end=505
  _globals['_S3CREDENTIALSSERVICE']._serialized_start=508
  _globals['_S3CREDENTIALSSERVICE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
