# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from altastata.grpc.v1 import s3_credentials_pb2 as altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altastata/grpc/v1/s3_credentials_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class S3CredentialsServiceStub(object):
    """Per-session S3 SigV4 credentials for end users (post-login).
    See altastata-grpc/CONSOLE_ACCOUNT_SETUP_DESIGN.md §7.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueCredentials = channel.unary_unary(
                '/altastata.v1.S3CredentialsService/IssueCredentials',
                request_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsResponse.FromString,
                _registered_method=True)
        self.ListMyCredentials = channel.unary_unary(
                '/altastata.v1.S3CredentialsService/ListMyCredentials',
                request_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsResponse.FromString,
                _registered_method=True)
        self.RevokeCredentials = channel.unary_unary(
                '/altastata.v1.S3CredentialsService/RevokeCredentials',
                request_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsRequest.SerializeToString,
                response_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsResponse.FromString,
                _registered_method=True)


class S3CredentialsServiceServicer(object):
    """Per-session S3 SigV4 credentials for end users (post-login).
    See altastata-grpc/CONSOLE_ACCOUNT_SETUP_DESIGN.md §7.

    """

    def IssueCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_S3CredentialsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueCredentials,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsResponse.SerializeToString,
            ),
            'ListMyCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyCredentials,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsResponse.SerializeToString,
            ),
            'RevokeCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredentials,
                    request_deserializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsRequest.FromString,
                    response_serializer=altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altastata.v1.S3CredentialsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altastata.v1.S3CredentialsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class S3CredentialsService(object):
    """Per-session S3 SigV4 credentials for end users (post-login).
    See altastata-grpc/CONSOLE_ACCOUNT_SETUP_DESIGN.md §7.

    """

    @staticmethod
    def IssueCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.S3CredentialsService/IssueCredentials',
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.IssueCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.S3CredentialsService/ListMyCredentials',
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.ListMyCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altastata.v1.S3CredentialsService/RevokeCredentials',
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsRequest.SerializeToString,
            altastata_dot_grpc_dot_v1_dot_s3__credentials__pb2.RevokeCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
